//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheKitchen.UnitOfMeasurements.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheKitchen.UnitOfMeasurements.Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE recipeml PUBLIC &quot;-//FormatData//DTD RecipeML 0.5//EN&quot;  &quot;http://www.formatdata.com/recipeml/recipeml.dtd&quot;&gt;
        ///&lt;?xml-stylesheet href=&quot;dessert1.css&quot; type=&quot;text/css&quot;?&gt;
        ///&lt;recipeml version=&quot;0.5&quot;&gt;
        ///  &lt;recipe&gt;
        ///    &lt;head&gt;
        ///      &lt;title&gt;The Needless-Markman Hoax Chocolate-Chip Cookie&lt;/title&gt;
        ///    &lt;/head&gt;
        ///    &lt;ingredients&gt;
        ///      &lt;ing&gt;
        ///        &lt;amt&gt;&lt;qty&gt;2&lt;/qty&gt;&lt;unit&gt;cups&lt;/unit&gt;&lt;/amt&gt;
        ///        &lt;item&gt;butter&lt;/item&gt;
        ///      &lt;/ing&gt;
        ///      &lt;ing&gt;
        ///        &lt;amt&gt;&lt;qty&gt;4&lt;/qty&gt;&lt;un [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RecipeML1 {
            get {
                return ResourceManager.GetString("RecipeML1", resourceCulture);
            }
        }
    }
}
